name: Foundry
https://basescan.org/address/0x4756c26e01e61c7c2f86b10f4316e179db8f9425#code#F1#L16
https://basescan.org/address/0x4756c26e01e61c7c2f86b10f4316e179db8f9425#code#F2#L1
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci
https://basescan.org/address/0x4756c26e01e61c7c2f86b10f4316e179db8f9425#code#F3#L1
jobs:
  check:
    name: forge-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
https://basescan.org/address/0x4756c26e01e61c7c2f86b10f4316e179db8f9425#code#F4#L1
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
https://basescan.org/address/0x4756c26e01e61c7c2f86b10f4316e179db8f9425#code#F6#L1
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
https://basescan.org/address/0x4756c26e01e61c7c2f86b10f4316e179db8f9425#code#F7#L1
      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
        env:
          ETH_RPC_URL: "https://eth-mainnet.g.alchemy.com/v2/${{ secrets.PROTOCOL_ALCHEMY_KEY }}"
https://basescan.org/address/0x4756c26e01e61c7c2f86b10f4316e179db8f9425#code#F8#L1
https://basescan.org/address/0x4756c26e01e61c7c2f86b10f4316e179db8f9425#code#L1
